name: Build Windows Installer

on:
  push:
    branches:
      - main


jobs:

  build-windows:

    runs-on: windows-latest


    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin

      - name: Show target folder
        shell: powershell
        run: |
          Get-ChildItem target -Recurse

      - name: Build Jar
        run: mvn clean package

      - name: Check build output
        shell: powershell
        run: |
          Write-Host "Current directory:"
          pwd

          Write-Host "Root files:"
          Get-ChildItem

          Write-Host "Target folder:"
          Get-ChildItem target -Recurse

      - name: Download JavaFX
        run: |
          curl -L -o javafx.zip https://download2.gluonhq.com/openjfx/21.0.7/openjfx-21.0.7_windows-x64_bin-sdk.zip
          tar -xf javafx.zip

      - name: Create Runtime Image
        shell: powershell
        run: |
          jlink `
            --module-path "$env:JAVA_HOME\jmods;javafx-sdk-21.0.7\lib" `
            --add-modules java.base,java.desktop,java.logging,java.xml,jdk.unsupported,javafx.controls,javafx.fxml `
            --output runtime

      - name: Create Installer
        shell: powershell
        run: |
          jpackage `
            --name "Mileage Exception Tool" `
            --input target `
            --main-jar MilesSheetCreator-1.0-SNAPSHOT.jar `
            --main-class com.tdem.milesheetcreator.Launcher `
            --type exe `
            --runtime-image runtime `
            --win-menu `
            --win-shortcut `
            --icon car.ico


      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Mileage Exception Tool Windows
          path: "*.exe"